### PR TITLE
Fix styling of disabled segmented control

### PR DESCRIPTION
**Pull request by varungupta85**
Thanks @GantMan for the tip on how to fix the styling of the disabled control. Made the text background transparent and also renamed some styling variable names so that they are more readable.

### CODE REVIEW

**Comment by GantMan** [comment]
looks like conflicts on the PR @varungupta85

**Comment by varungupta85** [comment]
@GantMan merged the branch with the master which has resolved the conflicts

**Comment by GantMan** [comment]
Do you mind adding a screenshot to this PR?

**Comment by varungupta85** [comment]
Here are the screenshots from Android

**Disabled**
screen shot 2016-09-24 at 8 49 17 am

**Enabled**
screen shot 2016-09-24 at 8 50 49 am

**Pull request merged**
